### PR TITLE
Add: Win Resizer extension

### PR DESCRIPTION
**Pull request by DalpatRathore**
Hi! @markodenic, I have contributed two Chrome extensions namely -Githunt & Win Resizer this time.

Thanks!

### CODE REVIEW

**Comment by markodenic** [comment]
@DalpatRathore Please, split the resources into separate PRs. Thanks!

**Comment by DalpatRathore** [comment]
> Please, split the resources into separate PRs. Thanks!

Sorry! @markodenic  I didn't understand this??

**Comment by breakerh** [comment]
@DalpatRathore He meant that for you can close this PR and create 2 new ones.

One for Githunt and a new one for Win Resizer.

**Comment by DalpatRathore** [comment]
Sorry! @breakerh  Yet I don't understand why separate PRs for the same resources and two lines. Kindly please explain this for further contribution references, so that I can contribute accordingly. I have already made such and some other types of contributions this way only.

**Comment by DalpatRathore** [comment]
Contributed [Window Resizer](https://chrome.google.com/webstore/detail/window-resizer/kkelicaakdanhinjdeammmilcgefonfh?hl=en) - Resize the browser window to emulate various screen resolutions

**Pull request closed without merging**
