### PR TITLE
Fontend mentor, a platform for frontend challenges, can be accessed at https://www.frontendmentor.io/

### PR DESCRIPTION
**Pull request by temi0x**
Frontend Mentor is a platform, that provides frontend coding challenges to users, and also helps grade and review them. It has both a free, and a premium tier. The free tier offers much challenges, but the premium offers a lot more. Solutions can be reviewd by other users, and comments can also be made, by other users, if the owner decides to accept comments.

Happy Sunday 😀

### CODE REVIEW

**Comment by MarkoDenic** [comment]
Hi Temiloluwa. thanks for contributing to this project.

Please add only one resource per PR. And, also don't change the structure of the repo. If you think that we could improve the readability of the resources open an issue. The idea of the repo is to be as simple as possible.

**Comment by Temiloluwa-ade** [comment]
Hi Marko. 

Sorry, I made a PR with one resource, and didn't notice that it wasn't yet accepted, before making the second commit.

I'll delete the second resource, so you can merge the first.

**Comment by MarkoDenic** [comment]
Great. Can you also remove the formatting of the table of contents? We'll keep the format s simple as possible.

**Comment by Temiloluwa-ade** [comment]
There's been no change, with table of contents. Can you help point it out?

**Comment by MarkoDenic** [comment]
Sure. Can you check this commit?
https://github.com/MarkoDenic/web-development-resources/pull/1/commits/2acb28368d1ffbaf86c5c5f461d05787f2bca75e

**Comment by Temiloluwa-ade** [comment]
I've been able to make the changes
Thanks

Temiloluwa

**Comment by MarkoDenic** [comment]
Hi Temiloluwa.

Now it's good. One tiny last change left to do. The link is broken (https://.frontendmentor.io)? Can you please fix it? 

Thank you for your patience.

**Comment by Temiloluwa-ade** [comment]
Sure

I've done that now

**Comment by MarkoDenic** [comment]
Hi Temiloluwa. Thank you for your patience. Unfortunately, you changed the permissions on the files in this repo, probably unintentionally.

I will add Frontend Mentor as a resource myself. 
I'm encouraging you to add more resources to the repo in the future, but please check the code before doing the PR, so we don't lose that much time on fixes and communication.

Thanks.

**Comment by Temiloluwa-ade** [comment]
Thanks Marco

I'd do well to check everything I'm adding, before I make a pull request

**Comment by niro2-1** [comment]
This is a note for the maintainers.

**Pull request closed without merging**
