### PR TITLE
Added: Cssrepo A curated list of awesome frameworks, style guides, and other cool nuggets for writing amazing CSS  Site

### PR DESCRIPTION
**Pull request by CodeWhiteWeb**
Added:
A curated list of awesome frameworks, style guides, and other cool nuggets for writing amazing CSS
It is a List of awesome CSS frameworks.
Site :- https://cssrepo.com

### CODE REVIEW

**Comment by markodenic** [comment]
@CodeWhiteWeb This is a cool resource. But, can you please move it under the "Others" category? Thanks!

**Comment by CodeWhiteWeb** [comment]
sure

**Comment by CodeWhiteWeb** [comment]
I have few more resources I would like to add in this repo
so, do I have create a new pull request, or I can add in this same pull request?

**Review by markodenic — APPROVED** [review]

**Comment by markodenic** [comment]
@CodeWhiteWeb Please keep one resource per PR. Thanks.

**Pull request merged**
