### PR TITLE
add new resource

### PR DESCRIPTION
**Pull request by frankiefab100**
Added devchallenges.io under Coding challenges Platforms

### CODE REVIEW

**Comment by MarkoDenic** [comment]
Hi Franklin. Thanks for your contribution. Can you please, remove the formatting of the tables because I want to keep the repo as simple as possible and faster to maintain? Great resource though.

Thank you.

**Comment by frankiefab100** [comment]
Please, can you elaborate more. I found the formatting was in the main repo.

**Comment by MarkoDenic** [comment]
If you go to your commit (https://github.com/MarkoDenic/web-development-resources/pull/31/commits/3baa319d378ca16829a16ad822848fcec9288277), you can see it was added there. If it's easier for you, you can close this and open a new PR, but please check the code before submitting it.

Thanks.

**Comment by frankiefab100** [comment]
Okay, I will resolve it.

**Pull request closed without merging**
