### PR TITLE
my contribution

### PR DESCRIPTION
**Pull request by dkay9**

### CODE REVIEW

**Comment by breakerh** [comment]
@dkay9 please provide the direct url to the channel

**Comment by dkay9** [comment]
@breakerh sorry this is one of my first open source contributions and I'm thinking i got everything right. Do you mean the url to Leon Noel's channel on youtube?

**Comment by breakerh** [comment]
@dkay9 correct, the link you need is https://youtube.com/channel/UCGiRSHBdWuCgjgmPPz_13xw

Please make another PR with this link instead

**Comment by dkay9** [comment]
Ok I'll do that thanks

**Pull request closed without merging**
